default_ethereum_client_images:
### Consensus layer clients
  lighthouse: sigp/lighthouse:deneb-modern
  lodestar: chainsafe/lodestar:next
  nimbus: ethpandaops/nimbus:unstable
  prysm: ethpandaops/prysm:devnet8-fix
  prysm_validator: ethpandaops/prysm-validator:devnet8-fix
  teku: consensys/teku:develop
### Execution layer clients
  besu: ethpandaops/besu:main
  geth: ethpandaops/geth:lightclient-devnet-8
  erigon: ethpandaops/erigon:devel
  ethereumjs: ethpandaops/ethereumjs:master
  nethermind: nethermindeth/nethermind:cancun
  reth: ethpandaops/reth:main


default_tooling_images:
  xatu_sentry: ethpandaops/xatu:latest
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: ethpandaops/tx-fuzz:latest
  forkmon: skylenet/nodemonitor:darkmode
  forky: ethpandaops/forky:latest
  fauceth: skylenet/fauceth:fix_fee_estimation
  ethstats: skylenet/ethstats-server:poa-no-geoip
  homepage: ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: ethpandaops/checkpointz:0.0.10-dencun-debian
  blockscout: blockscout/blockscout:master
  beacon_metrics_gazer: dapplion/beacon-metrics-gazer:latest
  eth_fauceth: chainflag/eth-faucet:latest
  blobscan: blossomlabs/blobscan:latest
  blobscan_indexer: blossomlabs/blobscan-indexer:latest
  light_beaconchain_explorer: pk910/light-beaconchain-explorer:latest
